CREATE OR REPLACE VIEW VIEW_PROJECT_OUTCOMES AS
	SELECT PROJECTS.PROJECT_NICKNAME,
		CONSERVATION_PLANNING_AREAS.CPA_NAME,
		HABITAT_TYPES.LONG_FORM,
		HABITAT_TYPES.UNIT,
		SUM(HABITAT_OUTCOMES.QUANTITY) AS TOTAL_OUTCOMES,
		PROJECTS.COORDINATE_X,
		PROJECTS.COORDINATE_Y,
		PROJECTS.PROJECT_COMPLETION_DATE
	FROM HABITAT_OUTCOMES
	LEFT JOIN HABITAT_PARCELS ON HABITAT_OUTCOMES.PARCEL_ID = HABITAT_PARCELS.ID
	LEFT JOIN PROJECTS ON HABITAT_PARCELS.PROJECT_ID = PROJECTS.ID
	LEFT JOIN HABITAT_TYPES ON HABITAT_OUTCOMES.HABITAT_TYPE = HABITAT_TYPES.ID
	LEFT JOIN CONSERVATION_PLANNING_AREAS ON PROJECTS.CPA = CONSERVATION_PLANNING_AREAS.ID
	GROUP BY PROJECTS.PROJECT_NICKNAME,
		HABITAT_TYPES.LONG_FORM,
		HABITAT_TYPES.UNIT,
		CONSERVATION_PLANNING_AREAS.CPA_NAME,
		PROJECTS.COORDINATE_X,
		PROJECTS.COORDINATE_Y,
		PROJECTS.PROJECT_COMPLETION_DATE