CREATE OR REPLACE VIEW view_cosmos_targets AS
	SELECT COSMOS_TARGETS.QUANTITY,
		HABITAT_TYPES.UNIT,
		HABITAT_TYPES.LONG_FORM,
		CONSERVATION_PLANNING_AREAS.CPA_NAME,
		COSMOS_TARGETS.TARGET_DATE
	FROM COSMOS_TARGETS
	JOIN CONSERVATION_PLANNING_AREAS ON COSMOS_TARGETS.CPA = CONSERVATION_PLANNING_AREAS.ID
	JOIN HABITAT_TYPES ON COSMOS_TARGETS.HABITAT_TYPE = HABITAT_TYPES.ID;